### PR TITLE
Add monitoring spec

### PR DESCRIPTION
**Pull request by neo-liang-sap**

### CODE REVIEW

**Review by clebs — CHANGES_REQUESTED** [review]
Hi @neo-liang-sap,
thanks for your PR!

I just reviewed it and it looks good to me. Unfortunately the examples do no longer work giving the following error when running `terraform plan` or `terraform apply`:
```
Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

1 error occurred:
	* resource gardener_shoot: emailReceivers: Elem must be set for lists
```

Once this is solved it is good to merge.

**Comment by neo-liang-sap** [comment]
Hi @clebs 
Thanks for reviewing this.
I fixed missing elem issue - Elem must be set for TypeList

When i was doing test on my local machine - after building the provider in my local machine, i got one kubeconfig and edit the content of examples/aws/main.tf then i ran `terraform init` && `terraform plan` i got error message indicating i didn't set cabundle correctly.

image

Actually i've set Required attribute in https://github.com/neo-liang-sap/terraform-provider-gardener/blob/add_monitoring_spec/shoot/schema_aws.go#L193

But i don't know why terraform still has this error message.

Is there any place of code i missed to modify? sorry this is first time i'm contributing to this repo, new to extending terraform provider...

Thanks!

-Neo

**Comment by clebs** [comment]
Hi @neo-liang-sap,
I would suggest setting `Optional: true` in the `caBundle` schema instead of `Required: false`.

Since `false` is the zero value for booleans in go, the validator probably detects it as not set at all.

**Comment by neo-liang-sap** [comment]
Yes @clebs ! i use Optional: True and it works.
Thanks for pointing this out and i'm learning sth new.
-Neo

**Review by clebs — APPROVED** [review]
LGTM!

**Pull request merged**
