### PR TITLE
add service_endpoints property for Azure vnet

### PR DESCRIPTION
**Pull request by pzamzow**
This implements the following feature request: #49

### CODE REVIEW

**Comment by rakesh-garimella** [comment]
Hi Patrick
 thanks for your PR can you please sign the CLA.

**Comment by pzamzow** [comment]
@rakesh-garimella I signed the CLA now. For the other PR (#48) it also working, but not here.

**Comment by pzamzow** [comment]
Re-opened the PR. Now it is working...

**Review by suleymanakbas91 — APPROVED** [review]

**Pull request merged**
